#pragma once
#ifndef SONIC_AUSTREAM.H
#define SONIC_AUSTREAM_H


#include <iostream>
#include <Windows.h>
#include <conio.h>
#include <wchar.h>

using namespace std;

#define SN_UP L'î'
#define SN_DOWN L'V'
#define SN_RIGHT L'>'
#define SN_LEFT L'<'

#define SN_SHADE_NONE L' '
#define SN_SHADE_WHITE L'\x2593'
#define SN_SHADE_GREY L'\x2592'
#define SN_SHADE_BLACK L'\x2591'
#define SN_SHADE_FULL L'\x2588'

#define SN_SHADE_CORNER_UP_RIGHT L'\x2510'
#define SN_SHADE_CORNER_DOWN_RIGHT L'\x2518'
#define SN_SHADE_CORNER_UP_LEFT L'\x250C'
#define SN_SHADE_CORNER_DOWN_LEFT L'\x2514'

#define SN_SHADE_LINE_HORISONTAL L'\x2500'
#define SN_SHADE_LINE_VERTICAL L'\x2502'
#define SN_SHADE_LINE_VERTICAL_MIDDLE_RIGHT L'\x251C'
#define SN_SHADE_LINE_VERTICAL_MIDDLE_LEFT L'\x2524'
#define SN_SHADE_LINE_HORISONTAL_MIDDLE_UP L'\x2534'
#define SN_SHADE_LINE_HORISONTAL_MIDDLE_DOWN L'\x252C'
#define SN_SHADE_LINE_CROSS L'\x253C'

#define SN_SHADE_DOUBLE_CORNER_UP_RIGHT L'\x2557'
#define SN_SHADE_DOUBLE_CORNER_DOWN_RIGHT L'\x255D'
#define SN_SHADE_DOUBLE_CORNER_UP_LEFT L'\x2554'
#define SN_SHADE_DOUBLE_CORNER_DOWN_LEFT L'\x255A'

#define SN_SHADE_DOUBLE_LINE_HORISONTAL L'\x2550'
#define SN_SHADE_DOUBLE_LINE_VERTICAL L'\x2551'
#define SN_SHADE_DOUBLE_LINE_VERTICAL_MIDDLE_RIGHT L'\x2560'
#define SN_SHADE_DOUBLE_LINE_VERTICAL_MIDDLE_LEFT L'\x2563'
#define SN_SHADE_DOUBLE_LINE_HORISONTAL_MIDDLE_UP L'\x2569'
#define SN_SHADE_DOUBLE_LINE_HORISONTAL_MIDDLE_DOWN L'\x2566'
#define SN_SHADE_DOUBLE_LINE_CROSS L'\x256C'

#endif // !SONIC_AUSTREAM_H
